# -----------------------------------------------------------------------
# Filename: pubspec.yaml
# Original Author: Dan Grissom
# Creation Date: 5/18/2024
# Copyright: (c) 2024 CSC322
# Description: This file specifies the dependencies of Mobile Innovation
#              Concierge.
# -----------------------------------------------------------------------
#            ____      _      _   __  __   _       _     
#           / ___|    / \    (_) |  \/  | | |     | |    
#          | |       / _ \   | | | |\/| | | |     | |    
#          | |___   / ___ \  | | | |  | | | |___  | |___ 
#           \____| /_/   \_\ |_| |_|  |_| |_____| |_____|
# -----------------------------------------------------------------------
name: csc322_starter_app
description: "CSC 322 Starter App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.1+1

# -----------------------------------------------------------------------
# Allowed Flutter SDK Versions
# -----------------------------------------------------------------------
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.22.0 <4.0.0'

# -----------------------------------------------------------------------
# Dependencies
# -----------------------------------------------------------------------
dependencies:
  flutter:
    sdk: flutter

  flutter_sound_record_platform_interface: ^0.3.1
  googleapis_auth: ^1.6.0     # Used?
  flutter_background_service: ^5.0.7
  audio_session: ^0.1.19    # Used?
  loading_animation_widget: ^1.2.1
  flutter_secure_storage: ^9.2.2
  font_awesome_flutter: ^10.7.0
  riverpod_annotation: ^2.3.5
  permission_handler: ^11.3.1
  firebase_storage: ^11.7.7
  flutter_riverpod: ^2.5.1
  cloud_firestore: ^5.4.0
  flutter_slidable: ^3.1.1
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  speech_to_text: ^6.6.0
  flutter_sound: ^9.11.2
  auto_size_text: ^3.0.0
  wakelock_plus: ^1.2.7
  image_picker: ^1.1.1
  flutter_tts: ^4.1.0
  go_router: ^14.1.2
  logger: ^2.3.0
  lottie: ^3.1.2
  intl: ^0.19.0
  file_picker: ^8.0.7
  google_sign_in: ^6.2.2
  http: ^1.0.0
  syncfusion_flutter_calendar: ^27.1.58

dependency_overrides:
  flutter_secure_storage_web: ^2.0.0-beta.1
  # js: ^0.6.3

# -----------------------------------------------------------------------
# Dev Dependencies
# -----------------------------------------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter

# -----------------------------------------------------------------------
# Icon Displayed in OS
# -----------------------------------------------------------------------
flutter_launcher_icons:
  image_path_android: "images/logo.png"
  image_path_ios: "images/logo.png"
  android: true 
  ios: true
  remove_alpha_ios: true

  # riverpod_generator: ^2.4.2
  # riverpod_lint: ^2.3.12
  # flutter_lints: ^3.0.0
  # build_runner:
  # custom_lint:

# -----------------------------------------------------------------------
# Flutter Settings
# -----------------------------------------------------------------------
flutter:
  uses-material-design: true
  assets:
    - images/
    - animations/
    - assets/

