// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqlvrW6A84LMFUmzrjhY0CHtWhVaBw7No',
    appId: '1:669530336201:android:f5536a49880646319e1618',
    messagingSenderId: '669530336201',
    projectId: 'csc322finalprojectscratch',
    storageBucket: 'csc322finalprojectscratch.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApdKSS3LXIR1GQuE22sOCgfIboZIl4o90',
    appId: '1:669530336201:ios:61fcb3e7731a5eac9e1618',
    messagingSenderId: '669530336201',
    projectId: 'csc322finalprojectscratch',
    storageBucket: 'csc322finalprojectscratch.firebasestorage.app',
    iosBundleId: 'com.example.csc322FinalProjectScratch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApdKSS3LXIR1GQuE22sOCgfIboZIl4o90',
    appId: '1:669530336201:ios:61fcb3e7731a5eac9e1618',
    messagingSenderId: '669530336201',
    projectId: 'csc322finalprojectscratch',
    storageBucket: 'csc322finalprojectscratch.firebasestorage.app',
    iosBundleId: 'com.example.csc322FinalProjectScratch',
  );
}

